version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.36
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: games_exchange
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  game_exchange_api1:
    depends_on:
      - mysqldb
      - kafka
    build: ./Video Game API 1.9
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_DB: games_exchange
  game_exchange_api2:
    depends_on:
      - mysqldb
      - kafka
    build: ./Video Game API 1.9
    ports:
      - "8081:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_DB: games_exchange
  game_exchange_api3:
    depends_on:
      - kafka
      - mysqldb
    build: ./Video Game API 1.9
    ports:
      - "8082:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_DB: games_exchange
  web:
    depends_on:
    - game_exchange_api1
    - game_exchange_api2
    - game_exchange_api3
    build: ./games_proxy
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8084:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  emailservice:
    depends_on:
      - kafka
      - mysqldb
    build: ./EmailService
    ports:
      - "8090:8090"

volumes:
  web:
  mysql-data:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
